### ISSUE TITLE
[CRITICAL] Cannot parse volume header

### ISSUE THREAD

**Issue by dylzen** [Aorimn/dislocker#111]
Hello everyone! I hope someone can help me decrypt my locked drive and retrieve my files. I'm getting the error in the title trying to decrypt my external drive. This is my Terminal output:

root@laptop:~# dislocker -vvv -V /dev/sdb1 -u -- /mnt/stuff/
Sat Jun 17 10:52:14 2017 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Sat Jun 17 10:52:17 2017 [INFO] Volume has EOW_INFORMATION_OFFSET_GUID.
Sat Jun 17 10:52:17 2017 [ERROR] Failed to read in #3: Bad address
Sat Jun 17 10:52:17 2017 [ERROR] get_eow_information::Error, not all bytes read: -1, -8 expected (2).
Sat Jun 17 10:52:17 2017 [ERROR] Getting EOW information at offset c07f0000 failed
Sat Jun 17 10:52:17 2017 [ERROR] EOW volume GUID not supported.
Sat Jun 17 10:52:17 2017 [CRITICAL] Cannot parse volume header. Abort.

I am a Linux newbie and have no idea what to do to get my files back... I know the Bitlocker password but when I plug it in Windows 10 it says my Bitlocker encrypted drive is not compatible with this version of Windows, the one I used to lock it in the first place. I appreciate any help, thanks in advance!

**Comment by Aorimn** [comment]
Hi,
dislocker doesn't support the decryption of still-encrypting partition yet. As a general process, I wuld recommend you to boot on Windows, wait for the encryption to finish, and then dislocker should do its job. However, in your condition, you could try libbde or wait for dislocker to have the ability to decrypt encrypting partition.

**Comment by Rondom** [comment]
@Aorimn, is it possible to detect this in the code and maybe produce a more user-friendly log message?

**Comment by itskp** [comment]
Hi, 
My windows 10 has bitlocker encryption in progress and now when i unlock it entire windows freezes so the encryption is not yet complete.
i tried using dislocker using live ubuntu

This is my Terminal Output is:

root@laptop:~# dislocker -vvv -V /dev/sdb1 -u -- /mnt/stuff/
Sun Jun 25 15:52:14 2017 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Sun Jun 25 15:52:14 2017 [INFO] Compiled version: master:747cbd6
Sun Jun 25 15:52:14 2017 [INFO] Volume has EOW_INFORMATION_OFFSET_GUID.
Sun Jun 25 15:52:14 2017 [ERROR] Getting EOW information at offset c4920000 failed to pass the tests
Sun Jun 25 15:52:14 2017 [ERROR] EOW volume GUID not supported.
Sun Jun 25 15:52:14 2017 [CRITICAL] Cannot parse volume header. Abort.

**Comment by itskp** [comment]
@Aorimn My bitlocker drive has 1 TB of important data Please help

**Comment by rossica** [comment]
You need to figure out, and solve, whatever is causing Windows to freeze 
when the drive is unlocked and let it complete bitlocker encryption 
before you can use dislocker.
Some things that come to mind are:
1) Is the computer the drive is connected to really slow? Maybe it's 
freezing due to bitlocker encryption of the drive using all CPU. Or 
maybe another program is trying to scan the drive once it is unlocked. 
Make sure whatever program that is scanning the drive is disabled until 
you complete bitlocker encryption of the drive.

2) The drive hardware is failing and throwing errors, freezing windows 
and preventing bitlocker from completing encryption.  In this case, you 
must pause bitlocker encryption and copy your data off this drive onto 
another one immediately.  You can search online for instructions for how 
to pause/suspend bitlocker encryption.

There may be many other causes; the above are just speculations on my 
part, and you must do the due diligence in resolving the issue.

**Comment by VamPikmin** [comment]
I've come across the same problem and I thought I post a solution that worked for me:
To make matters worse, the user has forgotten their account password and I couldn't reset it because the drive refuses to mount in Linux.
Steps:
Boot from a Windows 10 USB stick or DVD, Select advanced and command prompt
Once there type:
manage-bde -status
For the C: drive the status message was
Conversion Status: Encryption in Progress
Percentage Encrypted: 91.1%

To turn off:
manage-bde -off c:

When you re-run the status command it will say decryption in progress, when it's done it should say Fully Decrypted

Reboot in Linux and you can mount your drive, etc

**Comment by McPoopyPants** [comment]
Did you make sure you mounted the correct disk?  try fdisk -l
When I first tried I did not realize my hd had a hidden reserved partition because I did not create it, I used gparted and GPT and created a single partition and still had to mount as below

su root
md /mnt/stuff
dislocker -v -V /dev/sdb2 -u -- /mnt/stuff/
mount -o loop,w /mnt/tmp/dislocker-file /mnt/stuff  (replace w with r for read only)
ls /mnt/stuff    (to see if it worked)

**Comment by Aorimn** [comment]
Thanks @McPoopyPants for the reply, it's completely accurate

**Comment by johnstonmj** [comment]
> Hi, dislocker doesn't support the decryption of still-encrypting partition yet. As a general process, I wuld recommend you to boot on Windows, wait for the encryption to finish, and then dislocker should do its job. However, in your condition, you could try libbde or wait for dislocker to have the ability to decrypt encrypting partition.

Just echoing that incomplete BitLocker encryption in Windows led to this error for me.
Allowing the encryption process to complete then allowed dislocker to proceed successfully.
