### ISSUE TITLE
Very slow performance

### ISSUE THREAD

**Issue by ochompsky** [Aorimn/dislocker#138]
I have a USB drive with bitlocker that im running on a Rock64 board.  

When I start writing, everything goes fast.  But within several seconds, speeds drop from 22 MB/s to about 3 MB/sec and stay there.  

The bottleneck is definitely related to Dislocker.  Removing encryption from the drive gives me normal and sustained speeds of 22 MB/sec.  

I can't understand what the issue is.  Is it CPU bound?  According to htop, im not maxing out any of the cores:

<img width="1324" alt="screen shot 2018-03-30 at 8 32 11 am" src="https://user-images.githubusercontent.com/22012386/38138040-7a7c53b0-33f6-11e8-84d5-9a833edaeb37.png">

**Comment by rossica** [comment]
I'm no expert, but this sounds like it might be a limitation of the FUSE
filesystem having to go back and forth between user mode and kernel mode.

**Comment by ochompsky** [comment]
Thanks for the response @rossica - unfortunately it's way above me.  Is that something that is in my control to change?  

If it helps, here is CPU usage by core:

<img width="1204" alt="screen shot 2018-03-30 at 8 55 14 am" src="https://user-images.githubusercontent.com/22012386/38167121-12b86940-34fe-11e8-80b8-723a2c0d4a4b.png">

**Comment by rossica** [comment]
Sadly, there's nothing a user can do, if I'm correct.
Do you have another USB drive (different brand) to see if it happens the 
same there too?

**Comment by VarunAgw** [comment]
Can confirm the issue too. It starts at 10 MBps and then stuck at 2 MBps on Raspberry Pi.

**Comment by qubeck** [comment]
Can confirm that too.

Managed to work around that by disabling paralel enc/decryption in sectors.c (with #define NB_THREAD 0).

Well, creating a thread every time a sector is being processed is always potentially costly in relation to the processing itself.

Probably it's better to put a worker poll instead and signaling them.

**Comment by szaimen** [comment]
> Managed to work around that by disabling paralel enc/decryption in sectors.c (with #define NB_THREAD 0).
Hey @qubeck, how did you do that?
Did you compile the program from source?
I wonder if there could be a switch somewhere in a dislocker config file to change this without having to compile from source?

**Comment by Aorimn** [comment]
This issue has been fixed in 0.7.2 (by removing this faulty threading), thanks for reporting it.

**Comment by szaimen** [comment]
@Aorimn thanks for your reply! Is there a way to get this version into Ubuntu focal fossa?
I would love to use this new version there!

**Comment by paulstelian97** [comment]
@Aorimn Could you make an actual thread pool? That's how you'd still take advantage of parallelism whenever needed, without the overhead of always creating a new kernel thread every time you handle a damn sector.

**Comment by szaimen** [comment]
BTW: I've tested the new release and the performance is much improved.
Instead of 10MB/s I get now sometimes 30MB/s. @Aorimn Thanks for this!

But in order to use it in production, it should at least result in 110MB/s for this drive. 
So maybe what @paulstelian97 suggested would be a good starting point?

**Comment by paulstelian97** [comment]
Oof, feels like AES intrinsics are kinda required (not sure if the code actually uses them when available). Plus the parallelism itself, of course.

**Comment by Aorimn** [comment]
> Is there a way to get this version into Ubuntu focal fossa?

I've contacted Debian's maintainer (who's the packager behind Ubuntu's if I understand correctly), I don't know when he'll be available and when the package will land in Ubuntu

> Could you make an actual thread pool?

That could improve the performances indeed, but I won't have time to integrate it in the current code, that's why I took the middle-ground of disable threading entirely by default.

> not sure if the code actually uses [AES intrinsics] when available

dislocker's using mbedtls and mbedtls does use CPU's AES instructions when available.

---- 

All in all, this performance issue needs to be investigated way more deeper than I can dedicate time for this now :(
