### ISSUE TITLE
Error "ruby/config.h" in compile time in Ubuntu 18.04

### ISSUE THREAD

**Issue by luchmedia** [Aorimn/dislocker#153]
This is the error:

In file included from /usr/include/ruby-2.5.0/ruby.h:33:0,
                 from /home/user/Download/dislocker-master/include/dislocker/ruby.h:35,
                 from /home/user/Download/dislocker-master/include/dislocker/accesses/accesses.h:38,
                 from /home/user/Download/dislocker-master/src/dislocker.c:36:
/usr/include/ruby-2.5.0/ruby/ruby.h:24:10: fatal error: ruby/config.h: File o directory not exist
 #include "ruby/config.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/dislocker.dir/build.make:62: recipe for target 'src/CMakeFiles/dislocker.dir/dislocker.c.o' failed
make[2]: *** [src/CMakeFiles/dislocker.dir/dislocker.c.o] Error 1
CMakeFiles/Makefile2:200: recipe for target 'src/CMakeFiles/dislocker.dir/all' failed
make[1]: *** [src/CMakeFiles/dislocker.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

It's possibile this error is made by new version of ruby package? What version is preferred?

**Comment by luchmedia** [comment]
#146

**Comment by icylogic** [comment]
Although it's closed, I want to give a workaround here:

1. check if `FindRuby.cmake` has already been installed by cmake (Might be in `/usr/share/cmake-3.10/Modules/`)
2. `rm cmake/FindRuby.cmake`
3. clean files generated by previous cmake command like `CMakeCache.txt`
4. retry cmake
    ```shell
    $ cmake .
  
    ...
    -- Found Ruby: /usr/bin/ruby (found version "2.5.1") 
    ...
    ```
5. `make`

I don't know what's the minimum cmake version that would work. But since you are using Ubuntu 18.04, cmake installed by apt should be newer than or equal to 3.10.

**Comment by DoctypeRosenthal** [comment]
Also look here:
https://github.com/Aorimn/dislocker/issues/148#issuecomment-389292304

Solved it for me.
