### ISSUE TITLE
Dislocker not applicable to Samsung HW encrypted (eDrive) SSD? 

### ISSUE THREAD

**Issue by Naklarsuper** [Aorimn/dislocker#155]
Have the SSD HW encrypted with Magician eDrive (Samsung Tool). 
Using TMP+Pre-boot-pin. 

Using dislocker gives the error message: 
"Error during reading the volume: not enough byte read."

I am trying the -p option with the recovery numeric pin to decrypt. 

What is the issue?
- the pre-boot pin? 
- the HW encryption? 
- something else?

**Comment by Aorimn** [comment]
Hi,

No idea exactly, there can be a lot of reasons. The main reason is that it's using TPM, which isn't possible to support in dislocker (but that doesn't seem to be the error here).
Another reason might be because this is hardware encryption, which is, I expect, another proprietary thing, totally different from the BitLocker implementation of the encryption process and its metadata.

**Comment by grmpyninja** [comment]
It has to be due to proprietary encryption in use or maybe different, not supported algorithm, because I used `dislocker` successfully a few days ago with a raw image using `dd` from my laptop with TPM enabled.  And naturally I had to use recoverypassword

**Comment by paulstelian97** [comment]
Dislocker cannot support TPM except when you use recovery password.

Hardware encryption works in weird ways. Windows may be aware and use hardware encryption instead of standard Bitlocker encryption in this case, which Dislocker cannot really support except in a case-by-case basis (and blindly since it would be too expensive for devs to actually get such a drive for every implementation of HW encryption)
