### ISSUE TITLE
Onedrive files not accessible

### ISSUE THREAD

**Issue by DoganM95** [Aorimn/dislocker#201]
Just mounted my C:/ windows partition successfully in ubuntu using the -p option and my recovery key. i am able to access all my files which are not connected to onedrive.

however, all files in User/OneDrive have a size of 25 bytes, cloud only files as well as local files which are being synced with onedrive.i assume there is some header information prefixed to files which are connected to onedrive, which dislocker is unable to recognize (yet?), leading leads to all files being 25 bytes in size.

could you please take a look at that?
tried an `ls -la`, shows `-> "unsupported reparse point"`  next to each file

**Comment by Rondom** [comment]
Your problem is not related to this project. This project is only concerned with the BitLocker-encryption. It It is very likely that MS' OneDrive implementation uses features in NTFS that are not understood by NTFS-3G.

Anyways, I strongly suggest not to mess with your OneDrive-dir on your Windows partition to avoid malfunction or possible data loss.

Instead, I suggest using https://github.com/abraunegg/onedrive to sync your OneDrive to your Linux partition!

**Comment by paulstelian97** [comment]
Agreed, OneDrive in Windows 8.1 and Windows 10 when online-only files support is enabled works in very weird ways and cannot be accessed by any non-Windows (and possibly even Windows 8 and older) due to weird reparse points being used. NTFS-3G only supports standard reparse points (symlinks, junctions, and behaves decently with volume mounts; OneDrive uses other kinds).

Not Dislocker-related. Dislocker is mounting the volume just fine and stuff outside OneDrive is perfectly accessible, right?

**Comment by Aorimn** [comment]
Considering the first sentence of the issue:
> Just mounted my C:/ windows partition successfully in ubuntu using the -p option and my recovery key. i am able to access all my files which are not connected to onedrive.

I'll consider dislocker is working fine and close the issue.
