### ISSUE TITLE
dislocker allows writing forbidden chars by NTFS

### ISSUE THREAD

**Issue by superbonaci** [Aorimn/dislocker#234]
Those chars like `?` will make filesystem corrupt when running `chkdsk` on Windows. Files with those characters will be moved to FOUND folders when chkdsk is ran in write mode.

![](https://i.imgur.com/OLAXNlI.png)

**Comment by Aorimn** [comment]
As explained on [another comment](https://github.com/Aorimn/dislocker/issues/233#issuecomment-755409600), dislocker operates at the block layer, almost doesn't understand the filesystem and doesn't deal with filesystem restrictions such as file names.

It might have happened due to the corruption described in https://github.com/Aorimn/dislocker/issues/233 though, more tests are needed to find if this issue is a duplicate with https://github.com/Aorimn/dislocker/issues/233 or if it's an NTFS driver issue. In the meantime, I'll close this one.
