### ISSUE TITLE
Issue with Yosemite

### ISSUE THREAD

**Issue by jlchatelain** [Aorimn/dislocker#28]
Hi

I am trying to build dislocker on Yosemite 10.10.2 which has fuse 2.7.5 already installed.
I am getting this error (see image):

![dislocker build fail](https://cloud.githubusercontent.com/assets/11235352/6420420/e2bc686a-be93-11e4-9c2e-b64da0788be3.jpg)

Were you able to build it on Yosemite before?

Regards and thank you

Jean-Luc

**Comment by Aorimn** [comment]
Hi

I actually don't have a Yosemite install but it seems you're not the only one experiencing problems with osxfuse install: http://ajmccluskey.com/2015/01/brew-encfs-osxfuse-yosemite-upgrade-problem/
I can't test his solution, but as it works for him, I'd recommend trying the steps he describes for installing osxfuse and then install dislocker.

**Comment by mologie** [comment]
The `dislocker.rb` script needs fixing for this issue to go away: Homebrew introduced the pseudo-dependency `:osxfuse` which must be used instead of `"osxfuse"` so that dependency resolution succeeds if the binary distribution of OS X FUSE is installed.

**Comment by Clasyk** [comment]
Submitted my dislocker.rb fix for OS X Yosemite - https://github.com/Aorimn/dislocker/pull/38 .

Apologies if I did it wrong, long time developer first time Git user here.

Additionally, PolarSSL must be compiled from source. The brew installed PolarSSL failed to cooperate and I simply gave up on it. Compiling from source after downloading PolarSSL & installing the revised dislocker.rb formula works like a charm.

OSXFUSE must also be downloaded and installed from the package rather than through Homebrew. This installs the signed version whereas brew installs unsigned and dislocker refuses to install.

Hope this helps anyone frustrated with getting dislocker to work on OS X Yosemite.

**Comment by Aorimn** [comment]
You did it perfectly, don't worry :+1: 

The PolarSSL problem might be due to the change in the library name, now called libmbedtls.a, which wasn't planned when this formula was written (fix is in the deveop branch). But I didn't thought downloading PolarSSL and compiling from source would solve the problem.

**Comment by Clasyk** [comment]
Yeah, I downloaded the old PolarSSL source (prior to the name change to mbed) only to make it work hahah. Figured it was the fastest way to get it working, just fork the darn thing the file it oh so wants.

**Comment by Clasyk** [comment]
Also to add, installing OSXFUSE directly from its package rendered TrueCrypt unusable. I was afraid installing TrueCrypt again would overwrite the OSXFUSE headers dislocker requires but after installation both seem to work just fine. So TrueCrypt users must reinstall TrueCrypt after building dislocker if they wish to use both.
