### ISSUE TITLE
The signature of the volume () doesn't match the BitLocker's one

### ISSUE THREAD

**Issue by Michoob** [Aorimn/dislocker#3]
Hi,

I have successfully installed dislocker, but when I am running dislocker -V '/Volumes/NO NAME' I am getting following error message:
Wed Jan 15 12:17:34 2014 [CRITICAL] The signature of the volume () doesn't match the BitLocker's one (-FVE-FS-). Abort.

'NO NAME' is the name of the USB key that I am using and that was BitLocked under Windows 7. I guess I might be doing something wrong...

FYI, I am running Mac OS X Mavericks 10.9.1 and I have compiled dislocker the standard way with OSXFUSE version 2.6.2.

Thanks in advance for your help!

**Comment by oxitech239** [comment]
Hi, what kind of effort would it take for dislocker to support FAT encrypted volumes ?

**Comment by Aorimn** [comment]
Hi, it's already available in the develop branch. The current effort right now is stabilizing the develop branch to merge it and release a new version.

**Comment by oxitech239** [comment]
Thanks, i'm not sure if i'm doing it right. I get a file dislocker-file which i cannot mount, file says it is data. I could not find an offset since fdisk -l does not recognise it as a disk volume etc.

Reg,

Joris

----- Oorspronkelijk bericht -----
Van: Aorimn <notifications@github.com>
Aan: Aorimn/dislocker <dislocker@noreply.github.com>
Cc: oxitech239 <oxitech@telenet.be>
Verzonden: Wed, 15 Jul 2015 22:55:30 +0200 (CEST)
Onderwerp: Re: [dislocker] The signature of the volume () doesn't match the BitLocker's one (#3)

Hi, it's already available in the develop branch. The current effort right now is stabilizing the develop branch to merge it and release a new version.

---

**Comment by Aorimn** [comment]
Could you then please open a new bug report and give detail on how you encrypted the USB drive (which Windows version, which filesystem is encrypted), on how you're trying to decrypt it, and so on?

If you're getting a dislocker-file, then it should be mountable, no offset could/should change that.

**Comment by oxitech239** [comment]
*blush* must be the mount command then , iek

**Comment by Aorimn** [comment]
I may have been misleading: it's not because dislocker should be able to present a valid FAT32 that it's actually happening. From all the tests I've done, dislocker presents valid FAT32 (even VFAT) partitions so mount is able to recognize them. However, I've been reported (yours for example) that some partitions aren't decryptable, even if I don't know why yet (so there's no need to blush :-)).

That's why I'd like to know everything about your set-up; in order to be able to reproduce the bug - that's what I'm missing so far. Don't hesitate to open a new bug report as this is not the same bug as the one genuinely exposed here.

**Comment by oxitech239** [comment]
Thank you for the report, i have to discuss with others before i can disclose such information. Can we turn this around and you guide me so i can investigate and report myself ?

Best Regards,

J.

----- Oorspronkelijk bericht -----
Van: Aorimn <notifications@github.com>
Aan: Aorimn/dislocker <dislocker@noreply.github.com>
Cc: oxitech239 <oxitech@telenet.be>
Verzonden: Fri, 24 Jul 2015 00:34:35 +0200 (CEST)
Onderwerp: Re: [dislocker] The signature of the volume () doesn't match the BitLocker's one (#3)

I may have been misleading: it's not because dislocker should be able to present a valid FAT32 that it's actually happening. From all the tests I've done, dislocker presents valid FAT32 (even VFAT) partitions so mount is able to recognize them. However, I've been reported (yours for example) that some partitions aren't decryptable, even if I don't know why yet (so there's no need to blush :-)).

That's why I'd like to know everything about your set-up; in order to be able to reproduce the bug - that's what I'm missing so far. Don't hesitate to open a new bug report as this is not the same bug as the one genuinely exposed here.

---

**Comment by Aorimn** [comment]
I'm not sure how to investigate it myself, so giving instructions is quite hard.
However I try to get an invalid partition presented by dislocker, I can't. I can't find how to reproduce the problem. Would it be possible for you to provide me a dummy encrypted partition, with nothing important on it, no confidential data, and a fake password (like "qwerty123" or equivalent)? That would help a lot!
Regards

**Comment by Aorimn** [comment]
Any news Joris?

**Comment by oxitech239** [comment]
Hi, 

Sorry, there's little chance i can continue on this. Unless i file a formal request at the company to be allowe to expose this configuration. If there is anything i can reveal in-line with the corporate regulations, i will. 

Best Regards, 

Joris 

----- Oorspronkelijk bericht -----

Van: "Aorimn" <notifications@github.com> 
Aan: "Aorimn/dislocker" <dislocker@noreply.github.com> 
Cc: "oxitech239" <oxitech@telenet.be> 
Verzonden: Zondag 6 september 2015 17:10:47 
Onderwerp: Re: [dislocker] The signature of the volume () doesn't match the BitLocker's one (#3) 



Any news Joris?

**Comment by Manouchehri** [comment]
@oxitech239 I don't see how a FAT32 BitLocker volume created with default settings would reveal any corporate regulations (aside from "you need to use BitLocker"). If showing the configuration reveals private corporate information, you have *far* more serious concerns.

@Aorimn What work is remaining before merging in develop to master?

**Comment by Aorimn** [comment]
I'm still trying to reproduce this bug, but to no avail. As I can't reproduce, I'll probably ignore this report.

Aside from this report, I've been waiting a little for a reply on the pull #37, but I won't wait very long. At worst, if I get an answer there after the merging, I'll remerge just after.

**Comment by oxitech239** [comment]
Thanks for the continued followup. I've switched to RedHat Linux and will try again on that platform.

Joris


----- Oorspronkelijk bericht -----
Van: Aorimn <notifications@github.com>
Aan: Aorimn/dislocker <dislocker@noreply.github.com>
Cc: oxITech <oxitech@telenet.be>
Verzonden: Sat, 21 Nov 2015 23:59:43 +0100 (CET)
Onderwerp: Re: [dislocker] The signature of the volume () doesn't match the BitLocker's one (#3)

I'm still trying to reproduce this bug, but to no avail. As I can't reproduce, I'll probably ignore this report.

Aside from this report, I've been waiting a little for a reply on the pull #37, but I won't wait very long. At worst, if I get an answer there after the merging, I'll remerge just after.

---

**Comment by oxitech239** [comment]
I understand, it is not my call but now it is my responsibility. I'll try again later.

JL

----- Oorspronkelijk bericht -----
Van: David Manouchehri <notifications@github.com>
Aan: Aorimn/dislocker <dislocker@noreply.github.com>
Cc: oxITech <oxitech@telenet.be>
Verzonden: Fri, 20 Nov 2015 20:05:56 +0100 (CET)
Onderwerp: Re: [dislocker] The signature of the volume () doesn't match the BitLocker's one (#3)

@oxitech239 I don't see how a FAT32 BitLocker volume created with default settings would reveal any corporate regulations (aside from "you need to use BitLocker"). If showing the configuration reveals private corporate information, you have *far* more serious concerns.

@Aorimn What work is remaining before merging in develop to master?

---

**Comment by Manouchehri** [comment]
Why not format a drive yourself at home to test?

**Comment by oxitech239** [comment]
I've been told the configuratino used was 'tweaked', hence it would not matter what i test at home.

----- Oorspronkelijk bericht -----
Van: David Manouchehri <notifications@github.com>
Aan: Aorimn/dislocker <dislocker@noreply.github.com>
Cc: oxITech <oxitech@telenet.be>
Verzonden: Sun, 22 Nov 2015 14:30:05 +0100 (CET)
Onderwerp: Re: [dislocker] The signature of the volume () doesn't match the BitLocker's one (#3)

Why not format a drive yourself at home to test?


---

**Comment by Manouchehri** [comment]
@oxitech239 Unless they rewrote a kernel driver themselves, it's still standard BitLocker (owned by Microsoft). As far as I know configuration settings are not intellectual property or trade secrets in any country.

@Aorimn I'm wondering if maybe he's changed the group policy to use 256-bit AES instead of the default 128-bit AES. Have you checked that?

**Comment by Aorimn** [comment]
@Manouchehri  I think I've already tested with 128- or 256-bit keys, but to be sure I'll retest all the possibilities.

@oxitech239 Would it be possible to know the partition's size or is it also secret (for whatever reason)?

**Comment by oxitech239** [comment]
I understand, but i'm not working for a grocery store and i was told this was off-limits to disclose. Sorry, it's just not working. I've validated what i'm doing is correct. Unless i'm offered with a procedure to analyse if what i'm doing is right or wrong i cannot continue, even if i want to. 

----- Oorspronkelijk bericht -----

Van: "David Manouchehri" <notifications@github.com> 
Aan: "Aorimn/dislocker" <dislocker@noreply.github.com> 
Cc: "oxITech" <oxitech@telenet.be> 
Verzonden: Maandag 23 november 2015 21:17:27 
Onderwerp: Re: [dislocker] The signature of the volume () doesn't match the BitLocker's one (#3) 



@oxitech239 Unless they rewrote a kernel driver themselves, it's still standard BitLocker (owned by Microsoft). As far as I know configuration settings are not intellectual property or trade secrets in any country. 

@Aorimn I'm wondering if maybe he's changed the group policy to use 256-bit AES instead of the default 128-bit AES. Have you checked that?

**Comment by Aorimn** [comment]
On a Windows 7 enterprise, I've tested all of the 4 encryption algorithms (AES128/256, with or without diffuser) and couldn't find any problem regarding mounting a 300MB partition.

**Comment by oxitech239** [comment]
I'll check this on the new RHEL7 system, it may be i've errored but as far as i know we've already made sure i done everything right.

Joris


----- Oorspronkelijk bericht -----
Van: Aorimn <notifications@github.com>
Aan: Aorimn/dislocker <dislocker@noreply.github.com>
Cc: oxITech <oxitech@telenet.be>
Verzonden: Sat, 28 Nov 2015 13:24:53 +0100 (CET)
Onderwerp: Re: [dislocker] The signature of the volume () doesn't match the BitLocker's one (#3)

On a Windows 7 enterprise, I've tested all of the 4 encryption algorithms (AES128/256, with or without diffuser) and couldn't find any problem regarding mounting a 300MB partition.

---

**Comment by Aorimn** [comment]
@oxitech239 any news?

**Comment by oxitech239** [comment]
thanks for the follow up, not any time soon




-------- Oorspronkelijk bericht --------
Van: Aorimn <notifications@github.com>
Verzonden: Sun Dec 06 14:58:52 CET 2015
Aan: Aorimn/dislocker <dislocker@noreply.github.com>
Cc: oxITech <oxitech@telenet.be>
Onderwerp: Re: [dislocker] The signature of the volume () doesn't match the BitLocker's one (#3)

@oxitech239 any news?

---
