### ISSUE TITLE
Error installing dislocker with brew AND through make in Mac OS X Darwin

### ISSUE THREAD

**Issue by AlanGartner** [Aorimn/dislocker#47]
Hello,

I can't manage to install dislocker. I have downloaded the most recent master version from github. 
I have also installed the prerequisites through brew, but I get: 
 
<img width="557" alt="capture d ecran 2015-08-17 a 10 44 57" src="https://cloud.githubusercontent.com/assets/3002623/9301242/4c981d8c-44cd-11e5-91d8-05e908826a0d.png">
___________________________________

And when I try installing it from source, I get following errors :
<img width="660" alt="capture d ecran 2015-08-17 a 10 48 11" src="https://cloud.githubusercontent.com/assets/3002623/9301272/7c0def88-44cd-11e5-80f7-e2d9219fa658.png">

Any help would be greatly appreciated. Thanks !
Gilles

**Comment by Aorimn** [comment]
Hi, sorry for being this late.

Is the version from the develop branch working for you? Is there other problems from this version?

**Comment by mjthompson** [comment]
Hi there, I had the same issue with master. When I tried develop, I got this:
<img width="591" alt="screen shot 2015-12-28 at 1 58 49 am" src="https://cloud.githubusercontent.com/assets/1522222/12011436/d7882260-ad06-11e5-9b85-cb039503fa78.png">

**Comment by mjthompson** [comment]
I had the same issue with master branch.

Using the develop branch, the dislocker.rb script is still downloading dislocker-0.4.2.zip and installing the master version which calls the non-existent "polarssl" instead of the correct mbedssl

<img width="591" alt="screen shot 2015-12-28 at 1 58 49 am" src="https://cloud.githubusercontent.com/assets/1522222/12011665/27e798b6-ad12-11e5-9e35-6598075e8a1c.png">

is there anything I can do?

**Comment by dorianmuthig** [comment]
Okay this should be a simple fix. In [dislocker.rb](https://github.com/Aorimn/dislocker/blob/f3d25db7c8d82809818e53684341c06dd51e08ec/src/dislocker.rb "src/dislocker.rb") on line 13 there is still a reference to polarssl as a requirement, by now it has been renamed to mbedtls as well. There have also been several newer versions since, and the check about which of the two is installed could likely safely be removed (not that it ever worked, because I'm not aware of that having been fixed in the version of Ruby installed on Macs by default).
The only changes to the file that I can see since the merge of #43 are added newlines, so it's essentially still as I left it.

The error you are getting is that you don't have mbedtls installed, and since the requirement is now named incorrectly, it won't be installed automatically anymore. The quick fix is probably running `brew install mbedtls` and hoping that it works.
I'll try to look at it and send you a new pull-request when I have the time to run the tests to ensure that it can work reliably.

**Comment by mjthompson** [comment]
I tried that actually - but I got this:
`brew install mbedtls
Warning: mbedtls-2.2.0 already installed`

Interestingly, this is the same output as:
`brew install polarssl
Warning: mbedtls-2.2.0 already installed`

Have I mucked up somehow?

**Comment by dorianmuthig** [comment]
No, you're not doing anything wrong per se, there have been changes made to `mbedtls` and the structure of its source code that now cause the application to longer build since that change was made.
You do not need to copy the includes, `make` should automatically find them, if `brew` has linked them.
You can try replacing the references to `sha2.h` with references to `sha256.h` and see if that works, but I can't make any promises. I haven't looked at what parts of that code `dislocker` is using precisely or were implemented in `mbedtls`'s `sha2.h`, but the SHA-2 set of hash digest algorithms also includes SHA-384 and SHA-512 in addition to SHA-256. You can always try to install the version of `mbedtls` that is named in the `dislocker.rb` file and get something that works, because `dislocker` doesn't use the certificate validation bits used in TLS (BitLocker software encryption doesn't need that), but you should install the current version after building, if you're using it with anything that requires it for PKI services, like openVPN or some SSH clients.

**Comment by Aorimn** [comment]
polarssl and mbedtls are indeed a same formula in homebrew.

You can use the dislocker.rb script which has been updated in the master branch in order to install dislocker. Don't forget to update your homebrew installation (using `brew update`) before installing dislocker.

This new version of dislocker should find the right shaXXX.h file and link correctly against libmbedcrypto.a (which is where crypto functions are stored).

**Comment by Aorimn** [comment]
Let me know if you have any other difficulty.

**Comment by mjthompson** [comment]
Hi Aorimn, thank you for the reply!

Unfortunately, even after updating brew, I'm still having the same issue. It's still trying to call polarssl:

<img width="716" alt="screen shot 2016-01-04 at 12 19 28 am" src="https://cloud.githubusercontent.com/assets/1522222/12079573/14c445c4-b279-11e5-8fe8-7cd2e44623e1.png">

**Comment by Aorimn** [comment]
It seems your dislocker formula isn't up-to-date and still tries to download the old version of dislocker. Where did you get this version? Could you try with [this one](https://github.com/Aorimn/dislocker/blob/master/src/dislocker.rb) (which is the one from version 0.5.1)?

**Comment by mjthompson** [comment]
Ah okay, I downloaded master branch and ran brew install dislocker.rb - that worked fine. Installed! 

Thanks for your assistance!

**Comment by Aorimn** [comment]
Great, that's good!
