### ISSUE TITLE
Double free in metadata.c ?

### ISSUE THREAD

**Issue by SlivTaMere** [Aorimn/dislocker#77]
Hello,
When I run metadata, fuse or file it crashed with a "double free of corruption" message.
I looked at the stack trace and each time it crashes at line 427 in metadata.c in function check_volume_header.
From my understanding, dis_free(eow_infos) is called two times if all checks pass, at lines 418 and 427 in metadata.c triggering the double free error.

I commented the line 427 and recompiled, seems working.

**Comment by Aorimn** [comment]
Hi,
There's indeed a double-free-corruption error on the EOW handling path. This error should have been fixed by commit d480c31 (which is in the develop branch). I didn't take the same approach as you, but that still should "work" (between quotes because handling of EOW volumes isn't supported yet).

**Comment by SlivTaMere** [comment]
Hello,
I actually found the issue #69 was the same thing, sorry for the repeat.
