### ISSUE TITLE
TPM+PIN support

### ISSUE THREAD

**Issue by sempervictus** [Aorimn/dislocker#95]
Based on what we're seeing in the issues and just trying to open a TPM encrypted bitlocker volume, it seems that dislocker does not seem to support these. Our setup is an AD joined host for which we have recovery keys, and they're not being accepted by dislocker as valid to decrypt the volume (get  "none of the provided decryption mean is decrypting the keys"). We're attempting decryption on the host which encrypted the disk, same TPM, same enrollment, etc, just booted from a thumb drive to Ubuntu and using a fresh build (today's master) from this repo.

Thanks for creating this tool, and any help you could provide in accessing these volumes.

**Comment by Aorimn** [comment]
If the TPM options while encrypting the device are the default ones, then supporting TPM - or TPM+whatever - will be impossible due to the measurement process: the measuring code just before booting into Linux won't give the right value to the TPM, thus the TPM won't give off the encryption key.

However, the recovery keys from your AD should work fine with dislocker, using the `-p`option. Can you provide me with the command line you're using and an output with the `-vvvv` option (changing any password to dummy ones)?

**Comment by bduff-sjm** [comment]
TPM should be OK _if_ the USB drive is plugged in after boot with respect to measurement.

**Comment by Aorimn** [comment]
@bduff-sjm the boot chain wouldn't be the same when booting a linux (either from second partition or from USB drive). If you plug the USB drive after measurement happens, then you're off booting Windows.

**Comment by paulstelian97** [comment]
I vote for closing this issue. The TPM will refuse to give the unlock key when you're not booting into the actual Windows install which you used to set up the device. You can only use the recovery key.

Safe Mode in Windows also has the TPM refuse, just as a heads-up.

**Comment by TorstenC** [comment]
@paulstelian97 Suppose the recovery key is lost, but the PIN is still known: Is it possible to boot into the Windows install which you used to set up the device, if this is corrupted and can't be recovered? If that is the case, please give a brief explanation of how.

Otherwise I am waiting for a fix of this issue. Currently it is not yet closed, fortunately.

**Comment by paulstelian97** [comment]
If Windows boots and is usable you can reexport the recovery key just fine or suspend encryption (in that case a cleartext protector is temporarily added and Dislocker can use it). In the latter case you should still extract said recovery key.

If Windows ain't booting, then that's toast.

**Comment by Aorimn** [comment]
For completeness about @paulstelian97 message (which is completely true), here's how you can get the "Numerical Password" (`-p` option of dislocker) back once you're logged in (the commands need to be ran on a Windows administrator prompt):
```
PS C:\WINDOWS\system32> manage-bde -status c:
BitLocker Drive Encryption: Configuration Tool version 10.0.17134
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

Volume C: []
[OS Volume]

    Size:                 475.90 GB
    BitLocker Version:    2.0
    Conversion Status:    Used Space Only Encrypted
    Percentage Encrypted: 100.0%
    Encryption Method:    XTS-AES 128
    Protection Status:    Protection On
    Lock Status:          Unlocked
    Identification Field: Unknown
    Key Protectors:
        TPM
        Numerical Password

PS C:\WINDOWS\system32> manage-bde -protectors -get c:
BitLocker Drive Encryption: Configuration Tool version 10.0.17134
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

Volume C: []
All Key Protectors

    TPM:
      ID: {31E7D042-DCDC-46A2-B1D0-6FFD469AA098}
      PCR Validation Profile:
        7, 11
        (Uses Secure Boot for integrity validation)

    Numerical Password:
      ID: {940014B5-9DCA-4033-877F-3C29A9BE1470}
      Password:
        XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX
```

The `XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX` part is what you're looking for.

To disable encryption (not "turn off"):
```
PS C:\WINDOWS\system32> manage-bde -protectors -disable c:
BitLocker Drive Encryption: Configuration Tool version 10.0.17134
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

Key protectors are disabled for volume C:.
```

One can turn it back on using this command:
```
PS C:\WINDOWS\system32> manage-bde -protectors -enable c:
BitLocker Drive Encryption: Configuration Tool version 10.0.17134
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

Key protectors are enabled for volume C:.
```

> Otherwise I am waiting for a fix of this issue. Currently it is not yet closed, fortunately.

Sorry, this issue cannot be fixed due to technical reasons (explained in multiple comments above).
